### ISSUE TITLE
Getting a error 405 when getting call details, even I am able to join the bot to the call 

### ISSUE THREAD

**Issue by paolamvhz** [microsoft/Broadcast-Development-Kit#16]
I have set up the solution locally and using postman, I am able to join the bot in to the call, with the follow response 
{"id":"1a1e7bef-720f-411c-82dc-164d3dc157fd","resource":{"id":"1a1e7bef-720f-411c-82dc-164d3dc157fd","meetingUrl":"REDACTED","meetingId":"REDACTED","state":0,"createdAt":"2021-08-18T00:51:22.4000531-05:00","startedAt":"0001-01-01T00:00:00","endedAt":"0001-01-01T00:00:00","meetingType":0,"botFqdn":"localhost:9442","botIp":null,"defaultPassphrase":null,"defaultLatency":0,"graphId":null,"streams":[],"injectionStream":null,"publicContext":{},"privateContext":{"streamKey":"FXOkPqTsekSi2gbIMQwgNw"}}}
but I am not able to get the details of the call, even when the bot has been added to the call.

**Comment by verdua** [comment]
@paolamvhz we reviewed the [documentation](https://github.com/microsoft/Broadcast-Development-Kit/tree/main/docs/how-to-use-the-solution#join-the-bot-into-a-meeting) and we found that we have an error on the method description in the section **_Get call details_**. The http verb for the endpoint _https://{{appServiceUrl}}/api/call/{{callId}}_ is **_GET_** and not **_POST_**. We will correct this in the documentation soon.

**_Postman example:_**
![image](https://user-images.githubusercontent.com/37675560/129907692-465ff18d-d555-4e27-a926-e7e5f17e80a8.png)

Also @paolamvhz, we recommend you remove the Meeting URL and Meeting Id from the JSON response you posted, as that could be sensitive information.

**Comment by verdua** [comment]
@paolamvhz could you get the call details?

**Comment by paolamvhz** [comment]
Yes thanks!!
