### ISSUE TITLE
Not able to extract stream due a get frames issue enve the request is 200

### ISSUE THREAD

**Issue by paolamvhz** [microsoft/Broadcast-Development-Kit#28]
Hello team I am creating  request to extract a video but all the time seem like the video cannot be encoded due a lot of issues even when the request result is 200,

I already reviewed de firewall and enable the rtmp port go through it and I am running everything in vs in administrator mode.
[19:18:25 INF] [MediaPipeline] default message type: StreamStart, from element: pipeline0
0:06:22.883631100 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:948:gst_ffmpegviddec_get_buffer2:<video_decoder> Couldn't get codec frame !
0:06:22.904296300 26852 0000026AAE6A0A40 ERROR                  libav :0:: get_buffer() failed
0:06:22.908466100 26852 0000026AAE6A0A40 ERROR                  libav :0:: thread_get_buffer() failed
0:06:22.927445400 26852 0000026AAE6A0A40 ERROR                  libav :0:: decode_slice_header error
0:06:22.937077700 26852 0000026AAE6A0A40 ERROR                  libav :0:: no frame!
0:06:22.948343300 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:1954:gst_ffmpegviddec_handle_frame:<video_decoder> Failed to send data for decoding
0:06:22.968263300 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:948:gst_ffmpegviddec_get_buffer2:<video_decoder> Couldn't get codec frame !
0:06:22.998834300 26852 0000026AAE6A0A40 ERROR                  libav :0:: get_buffer() failed
0:06:23.006030000 26852 0000026AAE6A0A40 ERROR                  libav :0:: thread_get_buffer() failed
0:06:23.016378800 26852 0000026AAE6A0A40 ERROR                  libav :0:: decode_slice_header error
0:06:23.025983500 26852 0000026AAE6A0A40 ERROR                  libav :0:: no frame!
0:06:23.031853300 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:1954:gst_ffmpegviddec_handle_frame:<video_decoder> Failed to send data for decoding
0:06:23.552056900 [19:18:26 INF] [MediaPipeline] Pipeline state changed message from: rtmp_output, current state: Paused[19:18:26 INF] [MediaPipeline] default message type: Element, from element: audio_identity
26852 0000026AAE6A0980 FIXME             aggregator gstaggregator.c:1367:gst_aggregator_aggregate_func:<muxer> Subclass should call gst_aggregator_selected_samples() from its aggregate implementation.
[19:18:27 INF] [MediaPipeline] default message type: AsyncDone, from element: pipeline0
0:06:25.549771000 26852 0000026AAE6A0980 WARN                  flvmux gstflvmux.c:1249:gst_flv_mux_buffer_to_tag_internal:<muxer:sink_0> Got backwards dts! (0:00:19.845000000 < 0:00:21.280000000)
0:06:25.651618900 26852 0000026AAE6A0980 WARN                  flvmux gstflvmux.c:1249:gst_flv_mux_buffer_to_tag_internal:<muxer:sink_0> Got backwards dts! (0:00:19.868000000 < 0:00:21.280000000)
0:06:27.315000100 26852 0000026AAE6A0980 WARN                  flvmux gstflvmux.c:1249:gst_flv_mux_buffer_to_tag_internal:<muxer:sink_0>[19:18:29 INF] [MediaPipeline] Pipeline state changed message from: rtmp_output, current state: Playing
 Got backwards dts! (0:00:20.797000000 < 0:00:21.280000000)
[19:18:30 INF] [MediaPipeline] Pipeline state changed message from: pipeline0, current state: Playing
0:06:28.685055500 26852 0000026AAE6A0940 ERROR                   rtmp :0:: RTMP_Connect0, failed to connect socket. 10061 (Unknown error)
0:06:28.689307000 26852 0000026AAE6A0940 WARN                rtmpsink gstrtmpsink.c:294:gst_rtmp_sink_render:<rtmp_output> error: Could not connect to RTMP stream "rtmp://localhost:1940/extraction/lMEUM3UPkcXZrZdaZgw" for writing
0:06:28.837478900 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:948:gst_ffmpegviddec_get_buffer2:<video_decoder> Couldn't get codec frame !
0:06:28.843662900 26852 0000026AAE6A0A40 ERROR                  libav :0:: get_buffer() failed
0:06:28.848067600 26852 0000026AAE6A0A40 ERROR                  libav :0:: thread_get_buffer() failed
0:06:28.853233300 26852 0000026AAE6A0A40 ERROR                  libav :0:: decode_slice_header error
0:06:28.864852300 26852 0000026AAE6A0A40 ERROR                  libav :0:: no frame!
0:06:28.870193300 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:1954:gst_ffmpegviddec_handle_frame:<video_decoder> Failed to send data for decoding
0:06:28.881774900 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:948:gst_ffmpegviddec_get_buffer2:<video_decoder> Couldn't get codec frame !
0:06:28.938859700 26852 0000026AAE6A0A40 ERROR                  libav :0:: get_buffer() failed
0:06:28.957474000 26852 0000026AAE6A0A40 ERROR                  libav :0:: thread_get_buffer() failed
0:06:29.029450700 26852 0000026AAE6A0A40 ERROR                  libav :0:: decode_slice_header error
0:06:29.033843500 26852 0000026AAE6A0A40 ERROR                  libav :0:: no frame!
0:06:29.041696500 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:1954:gst_ffmpegviddec_handle_frame:<video_decoder> Failed to send data for decoding
0:06:29.127294900 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:948:gst_ffmpegviddec_get_buffer2:<video_decoder> Couldn't get codec frame !
0:06:29.147238900 26852 0000026AAE6A0A40 ERROR                  libav :0:: get_buffer() failed
0:06:29.151839200 26852 0000026AAE6A0A40 ERROR                  libav :0:: thread_get_buffer() failed
0:06:29.170947200 26852 0000026AAE6A0A40 ERROR                  libav :0:: decode_slice_header error
0:06:29.174017100 26852 0000026AAE6A0A40 ERROR                  libav :0:: no frame!
0:06:29.224844000 26852 0000026AAE6A0A40 WARN                   libav gstavviddec.c:1954:gst_ffmpegviddec_handle_frame:<video_decoder> Failed to send data for decoding

**Comment by sw-dcherubini** [comment]
@paolamvhz do you have any updates on your issues with RTMP?
