### ISSUE TITLE
Broken link to Prerequisites

### ISSUE THREAD

**Issue by JorgeALeitao** [microsoft/Broadcast-Development-Kit#3]
On the main page the link to Prerequisites points to https://github.com/microsoft/Broadcast-Development-Kit/blob/main/docs/prerequisites/readme.md which renders a 404.

https://github.com/microsoft/Broadcast-Development-Kit/blob/main/docs/prerequisites brings the content expected.

**Comment by AaronLinne** [comment]
Thanks! Got it cleared up now.
